name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Replace version in PHP file
        run: sed -i 's/{{VERSION}}/${{ steps.get_version.outputs.VERSION }}/g' src/betterportal-theme-embedded.php

      - name: Create release folder
        run: mkdir betterportal-theme-embedded

      - name: Copy files to release folder
        run: |
          cp -R src/* betterportal-theme-embedded/
          cp README.md betterportal-theme-embedded/
          cp LICENSE betterportal-theme-embedded/

      - name: Create ZIP archive
        run: zip -r betterportal-theme-embedded.zip betterportal-theme-embedded

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.get_version.outputs.VERSION }} \
            --title "Release ${{ steps.get_version.outputs.VERSION }}" \
            --notes "Release ${{ steps.get_version.outputs.VERSION }}" \
            betterportal-theme-embedded.zip
