name: Re-Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build plugin
        run: |
          chmod +x build.sh
          ./build.sh ${{ steps.get_version.outputs.VERSION }}
          
      - name: Create release artifact
        run: |
          chmod +x release.sh
          ./release.sh ${{ steps.get_version.outputs.VERSION }}

      - name: Create Release
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ steps.get_version.outputs.VERSION }} \
            --title "Release ${{ steps.get_version.outputs.VERSION }}" \
            --notes "Release ${{ steps.get_version.outputs.VERSION }}" \
            dist/betterportal-theme-embedded-${{ steps.get_version.outputs.VERSION }}.zip
      
      - name: Cleanup
        if: always()
        run: |
          rm -rf build dist
